package form;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import kripto.EnkripData;


/**
 *
 * @author Zierviera
 */
public class Encryption extends javax.swing.JFrame {
Dimension UM = Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form Encryption
     */
    public Encryption() {
        initComponents();
        this.setTitle("Encryption Form");
        setLocation(UM.width/2-getWidth()/2,UM.height/2-getHeight()/2);
        show(); 
        clear();
        tampilkanImage();
    }
    
   //Method Untuk Memanggil Image/gambar
 public static BufferedImage loadImage(String ref) {
 BufferedImage bimg = null;
 try {
 bimg = ImageIO.read(new File(ref));
 } catch (Exception e) {
 e.printStackTrace();
 }
 return bimg;
 }
 
 //Method untuk Resize Image
 public static BufferedImage resize(BufferedImage img, int
 newW, int newH) {    
 int w = img.getWidth();
 int h = img.getHeight();
 BufferedImage dimg = dimg = new BufferedImage(newW, newH,
 img.getType());
 Graphics2D g = dimg.createGraphics();
 g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
 RenderingHints.VALUE_INTERPOLATION_BILINEAR);
 g.drawImage(img, 0, 0, newW, newH, 0, 0, w, h, null);
 g.dispose();
 return dimg;
 }
 
//Method Untuk Menampilkan Gambar Pada JLabel
public void tampilkanImage(){
String urlGambar = "src/img/logo.png";
BufferedImage loadImg = loadImage(urlGambar);
ImageIcon imageIcon = new ImageIcon(resize(loadImg,
lblGambar.getWidth(), lblGambar.getHeight()));
lblGambar.setIcon(imageIcon);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCari = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        bgEncrypt1 = new img.bgEncrypt();
        lblInfo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtChooseFile = new javax.swing.JTextField();
        txtSave = new javax.swing.JTextField();
        txtChooseKey = new javax.swing.JTextField();
        bCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        bCFile = new javax.swing.JButton();
        bKey = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bEncrypt = new javax.swing.JButton();
        lblGambar = new javax.swing.JLabel();

        bCari.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Copyright 2015 By Bonta Zirviera Cirgon");

        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit2.png"))); // NOI18N
        bExit.setToolTipText("Back");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Choose File");
        jLabel7.setToolTipText("");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Choose Location");
        jLabel8.setToolTipText("");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Choose Public Key");
        jLabel9.setToolTipText("");

        txtChooseFile.setEditable(false);
        txtChooseFile.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        txtSave.setEditable(false);
        txtSave.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        txtChooseKey.setEditable(false);
        txtChooseKey.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        bCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.jpg"))); // NOI18N
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Encryption");

        bCFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/browse2.png"))); // NOI18N
        bCFile.setToolTipText("Browse File");
        bCFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCFileActionPerformed(evt);
            }
        });

        bKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/browse2.png"))); // NOI18N
        bKey.setToolTipText("Browse Public Key");
        bKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeyActionPerformed(evt);
            }
        });

        bSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/browse2.png"))); // NOI18N
        bSave.setToolTipText("Browse Save Location");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bEncrypt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bEncrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/process.jpg"))); // NOI18N
        bEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEncryptActionPerformed(evt);
            }
        });

        lblGambar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblGambar.setForeground(new java.awt.Color(255, 255, 255));
        lblGambar.setText(" ");

        javax.swing.GroupLayout bgEncrypt1Layout = new javax.swing.GroupLayout(bgEncrypt1);
        bgEncrypt1.setLayout(bgEncrypt1Layout);
        bgEncrypt1Layout.setHorizontalGroup(
            bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgEncrypt1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgEncrypt1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgEncrypt1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
            .addGroup(bgEncrypt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgEncrypt1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(bgEncrypt1Layout.createSequentialGroup()
                        .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChooseKey, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgEncrypt1Layout.createSequentialGroup()
                                .addComponent(bEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bKey, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bCFile, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(bgEncrypt1Layout.createSequentialGroup()
                        .addComponent(lblGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bgEncrypt1Layout.setVerticalGroup(
            bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEncrypt1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgEncrypt1Layout.createSequentialGroup()
                        .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(bKey, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChooseKey, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgEncrypt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addGap(261, 261, 261)
                .addComponent(lblInfo))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bgEncrypt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgEncrypt1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed
        
    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        clear();
    }//GEN-LAST:event_bCancelActionPerformed
    public void clear() {
        txtChooseFile.setText("");
        txtSave.setText("");
        txtChooseKey.setText("");
       }
    private void bCFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCFileActionPerformed
        JFileChooser datafile = new JFileChooser("D:\\tes source");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("File Document", "txt", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "pdf");
        FileNameExtensionFilter image = new FileNameExtensionFilter("File Images", "jpg", "jpeg","png", "bmp");
        FileNameExtensionFilter audio = new FileNameExtensionFilter("File Audio", "wav", "amr", "mp3");
        FileNameExtensionFilter files = new FileNameExtensionFilter("File", "zip", "rar");

        datafile.setFileFilter(image);
        datafile.setFileFilter(files);
        datafile.setFileFilter(audio);
        datafile.setFileFilter(filter);

        int returnVal = datafile.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = datafile.getSelectedFile();
            String dir = file.getAbsolutePath();

            txtChooseFile.setText(dir);
        }
    }//GEN-LAST:event_bCFileActionPerformed

    private void bKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeyActionPerformed
        JFileChooser dataFile = new JFileChooser("D:\\tes kunci");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("public key", "PublicKey");
        dataFile.setFileFilter(filter);
        dataFile.setAcceptAllFileFilterUsed(false);
        int returnVal = dataFile.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = dataFile.getSelectedFile();
            String dir = file.getAbsolutePath();
            txtChooseKey.setText(dir);
        }
    }//GEN-LAST:event_bKeyActionPerformed
    
    private void bEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEncryptActionPerformed
Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                String Kunci = (txtChooseKey.getText());
                String filename = (txtChooseFile.getText());
                String fileoutput = (txtSave.getText());
                int dot = filename.lastIndexOf(".");
                int sep = filename.replace("\\", "/").lastIndexOf("/");
                long start;
                long end;
                String detik;
                EnkripData enkrip = new EnkripData();
                if (!(Kunci.equals("") || filename.equals("") || fileoutput.equals(""))) {
                    try {                        
                        enkrip.setPublicKey(Kunci);
                        enkrip.setFile(fileoutput.replace("\\", "/"), filename.substring(sep + 1, dot), filename.substring(dot + 1));
                        start = System.currentTimeMillis();//menghitung waktu proses dalam detik
                        enkrip.encrypt(filename.replace("\\", "/"));
                        end = System.currentTimeMillis();
                        detik = String.valueOf(((end - start) / 1000.0));
                        
    JOptionPane.showMessageDialog(null, "File Successfully Encrypted!\nIn Time : "+detik+" Second(s)", "Encryption Success", JOptionPane.INFORMATION_MESSAGE);  
    
// menghapus file awal
   File dfile = new File(filename);
   dfile.delete();
   
   int confirm = JOptionPane.showConfirmDialog(null, "Do You Want To Add More Security?","Confirm", JOptionPane.YES_NO_OPTION);
   if(confirm == JOptionPane.YES_OPTION){
        EmbedFile em = new EmbedFile();
        em.setVisible(true);
        dispose();
        }
    else {
         JOptionPane.showMessageDialog(null, "File is saved at : " + enkrip.getFileNameEncrypt(), "Information", JOptionPane.INFORMATION_MESSAGE);
         clear();
        }                        
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Failed to Encryption", "Warning", JOptionPane.ERROR_MESSAGE);
                    }                    
                } else {
                    JOptionPane.showMessageDialog(null, "Fullfil the form, Please!", "Attention", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        t.start();   
    }//GEN-LAST:event_bEncryptActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
    JFileChooser savedata = new JFileChooser("D:\\");
        savedata.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = savedata.showSaveDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txtSave.setText(savedata.getSelectedFile().toString());
        }
    }//GEN-LAST:event_bSaveActionPerformed
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encryption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCFile;
    private javax.swing.JButton bCancel;
    private javax.swing.JMenuItem bCari;
    private javax.swing.JButton bEncrypt;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bKey;
    private javax.swing.JButton bSave;
    private img.bgEncrypt bgEncrypt1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTextField txtChooseFile;
    private javax.swing.JTextField txtChooseKey;
    private javax.swing.JTextField txtSave;
    // End of variables declaration//GEN-END:variables
}
